/* ALL PRODUCTS */
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

/* PRODUCTS DETAILS*/
export const PRODUCT_CREATE_REQUEST = 'PRODUCT_CREATE_REQUEST';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAILED = 'PRODUCT_DETAILS_FAILED';
export const PRODUCT_CREATE_RESET = 'PRODUCT_DETAILS_RESET';

/* PRODUCTS DETAILS*/
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED';

/* DELETE PRODUCTS */
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED';

/* UPDATE PRODUCTS */
export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED';
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET';

/* PRODUCTS REVIEW*/
export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST';
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS';
export const PRODUCT_CREATE_REVIEW_FAILED = 'PRODUCT_CREATE_REVIEW_FAILED';
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET';

/* TOP RATED PRODUCTS */
export const TOP_RATED_PRODUCT_REQUEST = 'TOP_RATED_PRODUCT_REQUEST';
export const TOP_RATED_PRODUCT_SUCCESS = 'TOP_RATED_PRODUCT_SUCCESS';
export const TOP_RATED_PRODUCT_FAILED = 'PRODUCT_CREATE_REVIEW_FAILED';