/* ALL PRODUCTS */
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';


/* DELETE PRODUCTS */
export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAILED = 'PRODUCT_DETAILS_FAILED';



/* PRODUCTS DETAILS*/
// export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
// export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
// export const PRODUCT_DETAILS_FAILED = 'PRODUCT_DETAILS_FAILED';